version: "3" # 버전 지정

services: # 컨테이너 설정
  backend:
    container_name: umc-service-dev
    image: kimjunseok/umcservice-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8000:8000

  redis:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379