version: "3" # 버전 지정

services: # 컨테이너 설정
  backend:
    container_name: umc-service-dev
    image: kimjunseok/umcservice-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    volumes:
      - ./my-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  redis:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379