version: "3" # 버전 지정

services: # 컨테이너 설정
  backend:
    container_name: umc-service-dev
    image: kimjunseok/umcservice-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8000:8000

  nginx:
    container_name: nginx-dev
    image: nginx:latest
    restart: always
    volumes:
      - ./my-nginx.conf:/etc/nginx/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  redis:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379