server:
  port: 8080
  url: http://localhost:8080

spring:
  application:
    name: umc-service-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    config:
      import: classpath:application.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true