server:
  port: 8080

spring:
  application:
    name: umc-service-prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    config:
      import: classpath:application.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul