server:
  port: 8000
  url: https://umcservice.shop

spring:
  application:
    name: umc-service-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    config:
      import: classpath:application.yml

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    org.springframework.web: ERROR
