package com.umc.networkingService.config.initial;

import com.umc.networkingService.global.common.enums.Part;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ProjectMemberInfo {

    // 3기
    BORA("보라", "유지수", Part.PM, ProjectInfo.TODAYSGYM.getName()),
    CHOROK("초록", "윤지민", Part.DESIGN, ProjectInfo.TODAYSGYM.getName()),
    BEX_1("벡스", "김준석", Part.ANDROID, ProjectInfo.TODAYSGYM.getName()),
    BORA_1("보라", "유지수", Part.SPRING, ProjectInfo.TODAYSGYM.getName()),
    HERON("헤론", "박세웅", Part.SPRING, ProjectInfo.TODAYSGYM.getName()),

    // 4기
    ARI("아리", "허영은", Part.PM, ProjectInfo.OWORI.getName()),
    LIBER_1("리버", "이경수", Part.IOS, ProjectInfo.OWORI.getName()),
    BEX_2("벡스", "김준석", Part.SPRING, ProjectInfo.OWORI.getName()),

    HANA_1("하나", "심세원", Part.ANDROID, ProjectInfo.MYOJIPSA.getName()),

    YENI_1("예니", "나예은", Part.IOS, ProjectInfo.ARF.getName()),


    LIBER("리버", "이경수", Part.PM, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    DELO("델로", "오정현", Part.DESIGN, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    DEUGI("더기", "양유진", Part.DESIGN, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    YENI("예니", "나예은", Part.IOS, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    WON("원", "김승원", Part.IOS, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    IDEUN("이든", "이태현", Part.IOS, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    NUNGGOCH("눈꽃", "정진혁", Part.WEB, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    YULI("율리", "김민지", Part.WEB, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    CHAISER("체이서", "최재혁", Part.WEB, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    LIO("리오", "이원영", Part.WEB, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    BEX("벡스", "김준석", Part.SPRING, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    LUCY("루시", "김수민", Part.SPRING, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    HANA("하나", "심세원", Part.SPRING, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    DAJEA("다재", "박재우", Part.SPRING, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    MIMBO("밈보", "김보민", Part.SPRING, ProjectInfo.UMC_NETWORKING_SERVICE.getName()),
    COGI("코기", "이명준", Part.PM, ProjectInfo.CAMPUS_NOTE.getName()),
    LILI("릴리", "김준휘", Part.DESIGN, ProjectInfo.CAMPUS_NOTE.getName()),
    LINA("리나", "한채연", Part.ANDROID, ProjectInfo.CAMPUS_NOTE.getName()),
    NECHEU("네츠", "박재원", Part.ANDROID, ProjectInfo.CAMPUS_NOTE.getName()),
    WILLOW("윌로우", "류남경", Part.ANDROID, ProjectInfo.CAMPUS_NOTE.getName()),
    HORANG("호랑", "이세원", Part.SPRING, ProjectInfo.CAMPUS_NOTE.getName()),
    EUNDING("은딩", "이은정", Part.SPRING, ProjectInfo.CAMPUS_NOTE.getName()),
    RUPI("류피", "김률아", Part.SPRING, ProjectInfo.CAMPUS_NOTE.getName()),
    MALZ("말즈", "김수환", Part.SPRING, ProjectInfo.CAMPUS_NOTE.getName()),
    HYEOKGU("혁규", "황규혁", Part.SPRING, ProjectInfo.CAMPUS_NOTE.getName()),
    PAUL("폴", "박경률", Part.PM, ProjectInfo.TEMBURIN.getName()),
    HYEPPY("혜피", "박혜란", Part.DESIGN, ProjectInfo.TEMBURIN.getName()),
    YERO("여로", "정현수", Part.ANDROID, ProjectInfo.TEMBURIN.getName()),
    MAX("맥스", "최윤석", Part.ANDROID, ProjectInfo.TEMBURIN.getName()),
    LIGHT("라이트", "김나경", Part.ANDROID, ProjectInfo.TEMBURIN.getName()),
    NORMAN("노먼", "박승태", Part.NODE, ProjectInfo.TEMBURIN.getName()),
    RUMI("루미", "김지혜", Part.NODE, ProjectInfo.TEMBURIN.getName()),
    IDEUN_2("이든", "오준석", Part.NODE, ProjectInfo.TEMBURIN.getName()),
    JAEHO("재호", "신재호", Part.NODE, ProjectInfo.TEMBURIN.getName()),
    ZAMMA("잼마", "유연수", Part.PM, ProjectInfo.HONJABDA.getName()),
    ZIMGING("짐깅", "이유진", Part.DESIGN, ProjectInfo.HONJABDA.getName()),
    MAKGU("맥구", "이재용", Part.IOS, ProjectInfo.HONJABDA.getName()),
    EEZE("이제", "황주연", Part.IOS, ProjectInfo.HONJABDA.getName()),
    CHERRY("체리", "이희주", Part.IOS, ProjectInfo.HONJABDA.getName()),
    EUNGEE("웅이", "김관주", Part.SPRING, ProjectInfo.HONJABDA.getName()),
    LOADING("로딩", "윤성문", Part.SPRING, ProjectInfo.HONJABDA.getName()),
    HUIRIRIK("휘리릭", "기승민", Part.SPRING, ProjectInfo.HONJABDA.getName()),
    ZERO("제로", "최준영", Part.SPRING, ProjectInfo.HONJABDA.getName()),
    MAISON("메이슨", "임민서", Part.PM, ProjectInfo.TAPE.getName()),
    EN("앤", "김민서", Part.DESIGN, ProjectInfo.TAPE.getName()),
    JUDI("주디", "방은서", Part.ANDROID, ProjectInfo.TAPE.getName()),
    CERNER("커너", "박성현", Part.ANDROID, ProjectInfo.TAPE.getName()),
    SSU("쑤", "김수민", Part.ANDROID, ProjectInfo.TAPE.getName()),
    COTTON("코튼", "양희연", Part.ANDROID, ProjectInfo.TAPE.getName()),
    SEO("세오", "오민석", Part.NODE, ProjectInfo.TAPE.getName()),
    BOB("밥", "이준수", Part.NODE, ProjectInfo.TAPE.getName()),
    COHI("코하이", "최형우", Part.NODE, ProjectInfo.TAPE.getName()),
    TORR("토르", "허민경", Part.NODE, ProjectInfo.TAPE.getName()),
    RAI("레이", "박륜", Part.NODE, ProjectInfo.TAPE.getName()),
    YEONLI("연리", "임수연", Part.PM, ProjectInfo.PLAN_ME.getName()),
    CLOI("클로이", "강지우", Part.DESIGN, ProjectInfo.PLAN_ME.getName()),
    SHEINA("셰이나", "박서현", Part.ANDROID, ProjectInfo.PLAN_ME.getName()),
    NUGURI("너구리", "고현철", Part.ANDROID, ProjectInfo.PLAN_ME.getName()),
    GAMJA("감자", "박혜정", Part.ANDROID, ProjectInfo.PLAN_ME.getName()),
    TIGER("티거", "김정효", Part.SPRING, ProjectInfo.PLAN_ME.getName()),
    COBI("코비", "이윤서", Part.SPRING, ProjectInfo.PLAN_ME.getName()),
    SNELL("스넬", "민성현", Part.SPRING, ProjectInfo.PLAN_ME.getName()),
    JAYCOB("제이콥", "임익주", Part.SPRING, ProjectInfo.PLAN_ME.getName()),
    SANSO("산소", "손호영", Part.SPRING, ProjectInfo.PLAN_ME.getName()),
    JUDER("주더", "최성준", Part.PM, ProjectInfo.UMJUMISIKHOI.getName()),
    SEURI("서리", "이윤설", Part.DESIGN, ProjectInfo.UMJUMISIKHOI.getName()),
    MOICHI("모이치", "이승민", Part.IOS, ProjectInfo.UMJUMISIKHOI.getName()),
    LIU("리우", "송민혁", Part.SPRING, ProjectInfo.UMJUMISIKHOI.getName()),
    JOA("조아", "조맑음", Part.PM, ProjectInfo.HAGOSIMDA.getName()),
    NEOJIN("너진", "이유진", Part.DESIGN, ProjectInfo.HAGOSIMDA.getName()),
    SIMI("시미", "심승보", Part.WEB, ProjectInfo.HAGOSIMDA.getName()),
    DAIZI("데이지", "이현진", Part.ANDROID, ProjectInfo.HAGOSIMDA.getName()),
    CHOCO("초코", "김현지", Part.SPRING, ProjectInfo.HAGOSIMDA.getName()),
    GUN("건", "이명건", Part.PM, ProjectInfo.MARIAJEU.getName()),
    OING("오잉", "김지오", Part.DESIGN, ProjectInfo.MARIAJEU.getName()),
    HANA_2("하나", "박하나", Part.ANDROID, ProjectInfo.MARIAJEU.getName()),
    RUNA("루나", "이은정", Part.WEB, ProjectInfo.MARIAJEU.getName()),
    TOPGUN("탑건", "오영수", Part.SPRING, ProjectInfo.MARIAJEU.getName()),
    HEIL("헤일", "이하연", Part.PM, ProjectInfo.CLIMUS.getName()),
    KELLY("켈리", "권나경", Part.DESIGN, ProjectInfo.CLIMUS.getName()),
    CROM("크롬", "변현섭", Part.ANDROID, ProjectInfo.CLIMUS.getName()),
    NERO("네로", "김선정", Part.ANDROID, ProjectInfo.CLIMUS.getName()),
    NOA("노아", "박진성", Part.ANDROID, ProjectInfo.CLIMUS.getName()),
    INOO("인우", "임용수", Part.ANDROID, ProjectInfo.CLIMUS.getName()),
    MUBIC("무빗", "가동식", Part.SPRING, ProjectInfo.CLIMUS.getName()),
    HUN("훈", "박성훈", Part.SPRING, ProjectInfo.CLIMUS.getName()),
    MIRI("미리", "박예림", Part.SPRING, ProjectInfo.CLIMUS.getName()),
    JINRO("진로", "박지운", Part.SPRING, ProjectInfo.CLIMUS.getName()),
    DAL("달", "박승준", Part.PM, ProjectInfo.REVIEW_ZIP.getName()),
    JENNY("제니", "김은서", Part.DESIGN, ProjectInfo.REVIEW_ZIP.getName()),
    UDI("우디", "김민우", Part.WEB, ProjectInfo.REVIEW_ZIP.getName()),
    DANG("댕", "정윤지", Part.SPRING, ProjectInfo.REVIEW_ZIP.getName()),
    RUNA_2("루나", "고지민", Part.PM, ProjectInfo.UMC_MATCHING_CENTER.getName()),
    DOBI("도비", "김도연", Part.DESIGN, ProjectInfo.UMC_MATCHING_CENTER.getName()),
    HANU("하누", "정현우", Part.WEB, ProjectInfo.UMC_MATCHING_CENTER.getName()),
    CHAN("찬", "김찬솔", Part.SPRING, ProjectInfo.UMC_MATCHING_CENTER.getName()),
    WIT("위트", "백재윤", Part.PM, ProjectInfo.RE_MEMORY.getName()),
    JAY("제이", "김세은", Part.DESIGN, ProjectInfo.RE_MEMORY.getName()),
    RICH("리치", "박시현", Part.WEB, ProjectInfo.RE_MEMORY.getName()),
    DERIC("데릭", "이동익", Part.NODE, ProjectInfo.RE_MEMORY.getName()),
    ;

    private final String nickname;
    private final String name;
    private final Part part;
    private final String projectName;
}
